"""changes in user table

Revision ID: 0b76ea985d03
Revises: 6b9ac9cbae48
Create Date: 2024-10-29 14:31:03.682638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b76ea985d03'
down_revision: Union[str, None] = '6b9ac9cbae48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('flowname', sa.String(), nullable=False))
    op.add_column('price', sa.Column('main_description', sa.String(), nullable=True))
    op.add_column('price', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('price', sa.Column('no_of_reviews', sa.Integer(), nullable=True))
    op.add_column('price', sa.Column('seller_type', sa.String(), nullable=True))
    op.add_column('price', sa.Column('availability', sa.Integer(), nullable=True))
    op.add_column('price', sa.Column('long_descrption', sa.String(), nullable=True))
    op.drop_column('price', 'fname')
    op.drop_column('price', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('price', sa.Column('fname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('price', 'long_descrption')
    op.drop_column('price', 'availability')
    op.drop_column('price', 'seller_type')
    op.drop_column('price', 'no_of_reviews')
    op.drop_column('price', 'rating')
    op.drop_column('price', 'main_description')
    op.drop_column('price', 'flowname')
    # ### end Alembic commands ###
