"""your_migration_message

Revision ID: 46819afbb830
Revises: c940530ce27f
Create Date: 2024-10-16 09:51:31.693715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46819afbb830'
down_revision: Union[str, None] = 'c940530ce27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('emailid', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('contactno', sa.Integer(), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fname')
    )
    op.create_index(op.f('ix_users_emailid'), 'users', ['emailid'], unique=True)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=True)
    op.drop_index('ix_user_emailid', table_name='user')
    op.drop_index('ix_user_password', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emailid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contactno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('zipcode', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('fname', name='user_fname_key')
    )
    op.create_index('ix_user_password', 'user', ['password'], unique=True)
    op.create_index('ix_user_emailid', 'user', ['emailid'], unique=True)
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_emailid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
