"""changes in user table

Revision ID: 6482c60a2668
Revises: 721ae58b89b6
Create Date: 2024-10-29 15:49:27.548903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6482c60a2668'
down_revision: Union[str, None] = '721ae58b89b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_column('price', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('price', 'date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    # ### end Alembic commands ###
