"""changed table schema for users

Revision ID: 6b9ac9cbae48
Revises: ec4a03bf30e6
Create Date: 2024-10-17 22:39:22.447527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9ac9cbae48'
down_revision: Union[str, None] = 'ec4a03bf30e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_fname_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_fname_key', 'users', ['fname'])
    # ### end Alembic commands ###
