"""Create flower table

Revision ID: dce5582be2e9
Revises: 58edc67cc1c8
Create Date: 2024-10-07 00:11:55.873906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce5582be2e9'
down_revision: Union[str, None] = '58edc67cc1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('time', sa.Time(), server_default=sa.text('CURRENT_TIME'), nullable=True),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('place', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('emailid', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('contactno', sa.Integer(), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fname')
    )
    op.create_index(op.f('ix_user_emailid'), 'user', ['emailid'], unique=True)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=True)
    op.drop_table('flower')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flower',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flower_pkey')
    )
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_emailid'), table_name='user')
    op.drop_table('user')
    op.drop_table('types')
    op.drop_table('price')
    op.drop_table('comments')
    # ### end Alembic commands ###
